---
- name: Create Apache Kafka input topic.
  shell: /usr/local/kafka_2.10-0.8.2.1/bin/kafka-topics.sh --create --zookeeper localhost:2181 --replication-factor 1 --partitions 1 --topic input-tweets

- name: Create Apache Kafka output topic.
  shell: /usr/local/kafka_2.10-0.8.2.1/bin/kafka-topics.sh --create --zookeeper localhost:2181 --replication-factor 1 --partitions 1 --topic output-results
